import { Inter, Open_Sans } from "next/font/google";
import BazaHeader from "./_TheHeader/BazaHeader";
import styles from "./page.module.css";
import { languages } from "../i18n/settings";
import { dir } from "i18next";
import "../globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const open_sans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html
      lang={lng}
      dir={dir(lng)}
      className={`${open_sans.variable} ${inter.variable}`}
    >
      <body>
        <BazaHeader lng={lng} />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}

// "use client";

// export default function GlobalError({ error, reset }) {
//   return (
//     <html>
//       <body>
//         <h2>Something went wrong!</h2>
//         <button onClick={() => reset()}>Try again</button>
//       </body>
//     </html>
//   );
// }
